# Generated by Django 5.0.1 on 2025-11-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.IntegerField(db_index=True, unique=True)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('avg_message_length', models.IntegerField(default=0)),
                ('response_time_pattern', models.JSONField(default=dict)),
                ('question_types', models.JSONField(default=list)),
                ('topics_discussed', models.JSONField(default=list)),
                ('sentiment_pattern', models.JSONField(default=dict)),
                ('conversation_length', models.IntegerField(default=0)),
                ('session_duration', models.FloatField(default=0.0)),
                ('follow_up_questions', models.IntegerField(default=0)),
                ('clarification_requests', models.IntegerField(default=0)),
                ('prefers_detailed_responses', models.BooleanField(null=True)),
                ('prefers_code_examples', models.BooleanField(null=True)),
                ('prefers_step_by_step', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', '-created_at'], name='chat_conver_user_id_1b35e3_idx')],
            },
        ),
        migrations.CreateModel(
            name='LearningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('event_type', models.CharField(choices=[('pattern_detected', 'Pattern Detected'), ('preference_learned', 'Preference Learned'), ('behavior_changed', 'Behavior Changed'), ('insight_generated', 'Insight Generated')], max_length=30)),
                ('description', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('confidence', models.FloatField(default=0.5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user_id', '-timestamp'], name='chat_learni_user_id_712e1d_idx'), models.Index(fields=['event_type'], name='chat_learni_event_t_cc7abe_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(choices=[('preference', 'User Preference'), ('pattern', 'Behavior Pattern'), ('topic', 'Topic Interest'), ('style', 'Communication Style'), ('context', 'Contextual Learning')], db_index=True, max_length=20)),
                ('key', models.CharField(max_length=255)),
                ('value', models.JSONField()),
                ('confidence', models.FloatField(default=0.5)),
                ('learned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_conversations', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-confidence', '-updated_at'],
                'indexes': [models.Index(fields=['user_id', 'category'], name='chat_userin_user_id_86c775_idx'), models.Index(fields=['user_id', 'key'], name='chat_userin_user_id_9a8937_idx'), models.Index(fields=['-confidence'], name='chat_userin_confide_6595ad_idx')],
                'unique_together': {('user_id', 'category', 'key')},
            },
        ),
    ]
